/**
 * Daftar lengkap error code API Gateway.
 * Konvensi: GW_<DOMAIN>_<REASON>
 * Kode STABIL — jangan pernah diubah setelah dipublikasikan.
 */
export enum ErrorCode {
  // ─── Auth ──────────────────────────────────────────────
  AUTH_MISSING = 'GW_AUTH_MISSING',
  AUTH_INVALID = 'GW_AUTH_INVALID',
  AUTH_TOKEN_EXPIRED = 'GW_AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_MALFORMED = 'GW_AUTH_TOKEN_MALFORMED',
  AUTH_TOKEN_REVOKED = 'GW_AUTH_TOKEN_REVOKED',
  AUTH_SIGNATURE_INVALID = 'GW_AUTH_SIGNATURE_INVALID',
  AUTH_ISSUER_INVALID = 'GW_AUTH_ISSUER_INVALID',
  AUTH_AUDIENCE_INVALID = 'GW_AUTH_AUDIENCE_INVALID',
  AUTH_JWKS_UNAVAILABLE = 'GW_AUTH_JWKS_UNAVAILABLE',
  AUTH_APIKEY_INVALID = 'GW_AUTH_APIKEY_INVALID',
  AUTH_APIKEY_REVOKED = 'GW_AUTH_APIKEY_REVOKED',
  AUTH_APIKEY_EXPIRED = 'GW_AUTH_APIKEY_EXPIRED',
  AUTH_MTLS_REQUIRED = 'GW_AUTH_MTLS_REQUIRED',
  AUTH_MTLS_INVALID = 'GW_AUTH_MTLS_INVALID',

  // ─── RBAC ──────────────────────────────────────────────
  RBAC_FORBIDDEN = 'GW_RBAC_FORBIDDEN',
  RBAC_ROLE_MISSING = 'GW_RBAC_ROLE_MISSING',
  RBAC_SCOPE_MISSING = 'GW_RBAC_SCOPE_MISSING',
  RBAC_TENANT_MISMATCH = 'GW_RBAC_TENANT_MISMATCH',
  RBAC_RESOURCE_DENIED = 'GW_RBAC_RESOURCE_DENIED',
  RBAC_POLICY_DENIED = 'GW_RBAC_POLICY_DENIED',

  // ─── Tenant ────────────────────────────────────────────
  TENANT_MISSING = 'GW_TENANT_MISSING',
  TENANT_UNKNOWN = 'GW_TENANT_UNKNOWN',
  TENANT_SUSPENDED = 'GW_TENANT_SUSPENDED',
  TENANT_INACTIVE = 'GW_TENANT_INACTIVE',
  TENANT_QUOTA_EXCEEDED = 'GW_TENANT_QUOTA_EXCEEDED',
  TENANT_MISMATCH = 'GW_TENANT_MISMATCH',

  // ─── Validation ────────────────────────────────────────
  VALIDATION_FAILED = 'GW_VALIDATION_FAILED',
  VALIDATION_BODY_INVALID = 'GW_VALIDATION_BODY_INVALID',
  VALIDATION_QUERY_INVALID = 'GW_VALIDATION_QUERY_INVALID',
  VALIDATION_PARAM_INVALID = 'GW_VALIDATION_PARAM_INVALID',
  VALIDATION_HEADER_MISSING = 'GW_VALIDATION_HEADER_MISSING',
  VALIDATION_HEADER_INVALID = 'GW_VALIDATION_HEADER_INVALID',
  VALIDATION_CONTENT_TYPE = 'GW_VALIDATION_CONTENT_TYPE',
  VALIDATION_ACCEPT = 'GW_VALIDATION_ACCEPT',
  VALIDATION_PAYLOAD_TOO_LARGE = 'GW_VALIDATION_PAYLOAD_TOO_LARGE',
  VALIDATION_SCHEMA_MISMATCH = 'GW_VALIDATION_SCHEMA_MISMATCH',

  // ─── Routing ───────────────────────────────────────────
  ROUTE_NOT_FOUND = 'GW_ROUTE_NOT_FOUND',
  ROUTE_METHOD_NOT_ALLOWED = 'GW_ROUTE_METHOD_NOT_ALLOWED',
  ROUTE_DISABLED = 'GW_ROUTE_DISABLED',
  ROUTE_DEPRECATED = 'GW_ROUTE_DEPRECATED',
  ROUTE_UPSTREAM_MISSING = 'GW_ROUTE_UPSTREAM_MISSING',
  ROUTE_CONFIG_INVALID = 'GW_ROUTE_CONFIG_INVALID',
  ROUTE_LOOP_DETECTED = 'GW_ROUTE_LOOP_DETECTED',

  // ─── Rate Limit & Quota ────────────────────────────────
  RATE_LIMIT_EXCEEDED = 'GW_RATE_LIMIT_EXCEEDED',
  RATE_LIMIT_IP_EXCEEDED = 'GW_RATE_LIMIT_IP_EXCEEDED',
  RATE_LIMIT_USER_EXCEEDED = 'GW_RATE_LIMIT_USER_EXCEEDED',
  RATE_LIMIT_TENANT_EXCEEDED = 'GW_RATE_LIMIT_TENANT_EXCEEDED',
  RATE_LIMIT_ROUTE_EXCEEDED = 'GW_RATE_LIMIT_ROUTE_EXCEEDED',
  RATE_LIMIT_BURST_EXCEEDED = 'GW_RATE_LIMIT_BURST_EXCEEDED',
  RATE_LIMIT_STORE_UNAVAILABLE = 'GW_RATE_LIMIT_STORE_UNAVAILABLE',
  QUOTA_DAILY_EXCEEDED = 'GW_QUOTA_DAILY_EXCEEDED',
  QUOTA_MONTHLY_EXCEEDED = 'GW_QUOTA_MONTHLY_EXCEEDED',

  // ─── Idempotency ───────────────────────────────────────
  IDEMP_KEY_MISSING = 'GW_IDEMP_KEY_MISSING',
  IDEMP_KEY_INVALID = 'GW_IDEMP_KEY_INVALID',
  IDEMP_IN_PROGRESS = 'GW_IDEMP_IN_PROGRESS',
  IDEMP_CONFLICT = 'GW_IDEMP_CONFLICT',
  IDEMP_EXPIRED = 'GW_IDEMP_EXPIRED',
  IDEMP_STORE_UNAVAILABLE = 'GW_IDEMP_STORE_UNAVAILABLE',

  // ─── Circuit Breaker ───────────────────────────────────
  CIRCUIT_OPEN = 'GW_CIRCUIT_OPEN',
  CIRCUIT_HALF_OPEN_REJECTED = 'GW_CIRCUIT_HALF_OPEN_REJECTED',
  CIRCUIT_FORCED_OPEN = 'GW_CIRCUIT_FORCED_OPEN',
  BULKHEAD_REJECTED = 'GW_BULKHEAD_REJECTED',

  // ─── Upstream ──────────────────────────────────────────
  UPSTREAM_UNAVAILABLE = 'GW_UPSTREAM_UNAVAILABLE',
  UPSTREAM_TIMEOUT = 'GW_UPSTREAM_TIMEOUT',
  UPSTREAM_CONNECT_FAILED = 'GW_UPSTREAM_CONNECT_FAILED',
  UPSTREAM_ERROR = 'GW_UPSTREAM_ERROR',
  UPSTREAM_INVALID_RESPONSE = 'GW_UPSTREAM_INVALID_RESPONSE',
  UPSTREAM_TLS_ERROR = 'GW_UPSTREAM_TLS_ERROR',
  UPSTREAM_DNS_FAILED = 'GW_UPSTREAM_DNS_FAILED',
  UPSTREAM_RETRY_EXHAUSTED = 'GW_UPSTREAM_RETRY_EXHAUSTED',
  UPSTREAM_PROTOCOL_ERROR = 'GW_UPSTREAM_PROTOCOL_ERROR',

  // ─── Cache ─────────────────────────────────────────────
  CACHE_STORE_UNAVAILABLE = 'GW_CACHE_STORE_UNAVAILABLE',
  CACHE_KEY_INVALID = 'GW_CACHE_KEY_INVALID',

  // ─── Internal ──────────────────────────────────────────
  INTERNAL_ERROR = 'GW_INTERNAL_ERROR',
  INTERNAL_CONFIG_ERROR = 'GW_INTERNAL_CONFIG_ERROR',
  INTERNAL_DEPENDENCY_ERROR = 'GW_INTERNAL_DEPENDENCY_ERROR',
  INTERNAL_NOT_IMPLEMENTED = 'GW_INTERNAL_NOT_IMPLEMENTED',
  INTERNAL_MAINTENANCE = 'GW_INTERNAL_MAINTENANCE',

  // ─── Ops / Admin ───────────────────────────────────────
  OPS_UNAUTHORIZED = 'GW_OPS_UNAUTHORIZED',
  OPS_FORBIDDEN = 'GW_OPS_FORBIDDEN',
  OPS_RATE_LIMITED = 'GW_OPS_RATE_LIMITED',
  OPS_RELOAD_IN_PROGRESS = 'GW_OPS_RELOAD_IN_PROGRESS',
  OPS_INVALID_CONFIG = 'GW_OPS_INVALID_CONFIG',
  OPS_METRICS_UNAVAILABLE = 'GW_OPS_METRICS_UNAVAILABLE',
}

export type ErrorCodeType = keyof typeof ErrorCode;
export type ErrorCodeValue = `${ErrorCode}`;