global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: michishirube
    env: ${NODE_ENV:-development}

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:9464']
        labels:
          service: api-gateway
          component: gateway

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
